#!/bin/bash
noarg()
{
    echo "You have not provided an argument"
    echo "When using this script, you need to specify a filename"
    exit 2
}

if [ -z "$1" ]; then
    noarg
else
    file "$1"
fi
exit 0
